### ISSUE TITLE
hilt error at build project

### ISSUE THREAD

**Issue by rogergcc** [ydhnwb/android-cache-example#1]
cannot access DefaultActivityViewModelFactory

![image](https://user-images.githubusercontent.com/18008332/134074246-90047344-d129-481e-a61d-3db9aedee409.png)

i need a min version of android studio IDE or Kotlin?

**Comment by ydhnwb** [comment]
I'm using Android Studio Arctic Fox 2020.3.1 Patch 2 on Linux.
When the project build for the first time, it shows an error (gradle error), after I "Invalidate chache and restart" the problem gone and projects runs perfectly.

For your problem, try to Invalidate Cache and Restart ( File > Invalidate Cache and Restart), then rebuild your project.

**Comment by rogergcc** [comment]
idk how to solve it 😔.
maybe is the verision of HILT or Android Studio or jdk or kotlin? 😥

![image](https://user-images.githubusercontent.com/18008332/134210635-01bebcc1-3ad0-47a3-9348-d82cc4701d17.png)

my android studio
![image](https://user-images.githubusercontent.com/18008332/134211090-be46fa5c-1374-4eed-be4e-b2c72bee36df.png)

**Comment by rogergcc** [comment]
Hi idk if is for version of A.S but this works for me. 
 
```// dagger - Hilt 
//ext.dagger_hilt_version = "2.38.1"
    implementation "com.google.dagger:hilt-android:$dagger_hilt_version"
    kapt "com.google.dagger:hilt-android-compiler:$dagger_hilt_version"
    kapt "com.google.dagger:hilt-compiler:2.37"
```
